package ChiselLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ArithExp_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Computation_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Input_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Integer_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Party_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new PartyDeclaration_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new PartyRef_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new Protocol_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new PartyRef_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bcd1c7eL), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bc814b2L), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bc78ef1L), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bca41cfL), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bc78ee1L), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bd30f19L), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bd1e1fbL), MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bc814b3L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x834a4f2193844439L, 0xa5bea9f2ef9bfdf9L, 0x34ac754e3bd1e1fbL)).seal();
}
